controller_list:
  - name: ""
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - axis1_joint
      - axis2_joint
      - axis3_joint
      - axis4_joint
      - axis5_joint
      - axis6_joint
