joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

mobile_base_controller:
  type        : "diff_drive_controller/DiffDriveController"
  right_wheel : 'right_wheel_joint'
  left_wheel  : 'left_wheel_joint'
  publish_rate: 50.0               # default: 50
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  wheel_separation : 0.42
  wheel_radius : 0.1

  wheel_separation_multiplier: 1.05 # default: 1.09 for competition
  wheel_radius_multiplier    : 1.025 # default: 1.05 for competition

  cmd_vel_timeout: 0.25
  enable_odom_tf: false

  base_frame_id: base_footprint #default: base_link

  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.6  # m/s
      min_velocity           : -0.6 # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.5  # m/s^2
      min_acceleration       : -0.5 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0  # rad/s
      min_velocity           : -2.0  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 0.8  # rad/s^2
      min_acceleration       : -0.8  # rad/s^2
